services:
  raas:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - 9091:9091
    environment:
      REDIS_URL: redis://redis:6379
      USER_DATA_PATH: /data
      SECRET_KEY_PATH: /secret/secret_key
    volumes:
      - secret:/secret
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "pidof", "rce-as-a-service"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  redis:
    image: redis:7.4.2-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 512M

  cleaner:
    image: c4tbuts4d/dedcleaner:latest
    volumes:
      - user_data:/data
    environment:
      - DELETE_AFTER=20m
      - SLEEP=1m
      - DIRS=/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M

volumes:
  user_data:
  redis_data:
  secret:
