services:
  raas:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9091:9091
    environment:
      S3_URL: http://s3:8333
      DB_URL: postgres://postgres:postgres@db:5432/raas
      USER_LIFETIME_MINS: 20
      CLEANER_INTERVAL_MINS: 1
    depends_on:
      - db
      - s3
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  s3:
    build:
      context: ./s3
      dockerfile: Dockerfile
    command: server -s3
    volumes:
      - s3_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8333"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: raas
    ports: # TODO: Remove this
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: pg_isready -U postgres -d raas
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M

volumes:
  s3_data:
  db_data:
