services:
  raas:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - 9091:9091
    environment:
      REDIS_URL: redis://valkey:6379
      USER_DATA_PATH: /data
      SECRET_KEY_PATH: /secret/secret_key
    volumes:
      - secret:/secret
      - user_data:/data
    depends_on:
      - valkey
    healthcheck:
      test: ["CMD", "pidof", "rce-as-a-service"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  valkey:
    image: valkey/valkey:8.0.2-alpine
    command: ["valkey-server", "--appendonly", "yes"]
    volumes:
      - valkey_data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "--raw", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 512M

  cleaner:
    image: c4tbuts4d/dedcleaner:latest
    volumes:
      - user_data:/data
    environment:
      - DELETE_AFTER=20m
      - SLEEP=1m
      - DIRS=/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M

volumes:
  user_data:
  valkey_data:
  secret:
