services:
  magazinchik:
    build: ./task
    ports:
      - "8080:8080"
    restart: unless-stopped
    pids_limit: 256
    platform: linux/amd64
    mem_limit: 128M
    cpus: 0.5
    volumes:
      - "./tmp:/tmp"

  cleaner:
    image: c4tbuts4d/dedcleaner:latest
    restart: unless-stopped
    platform: linux/amd64
    volumes:
      - "./tmp:/tmp"
    environment:
      - DELETE_AFTER=15m
      - SLEEP=2m
      - DIRS=/tmp